name: On commit hook

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    container:
      image: node:12.13.0-alpine3.10
    steps:
      - uses: actions/checkout@v2.0.0
      - name: prepare environment
        run: npm install
      - name: lint
        run: npm run lint